name: examples-ci
on:
  pull_request:

defaults:
  run:
    working-directory: ./packages/examples

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v2
        with:
          runtime: node@22
          install: true
          cache: true

      - run: pnpm run build
      - run: pnpm run lint
