name: Release Library
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./packages/react-focus-rings

permissions:
  # To publish packages with provenance via OIDC
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v2
        with:
          runtime: node@22
          install: true
          cache: true

      - shell: sh
        run: |-
          git status
          pnpm publish --access public --provenance
